const state={user:null,devices:[],scenes:[],events:[],deployments:[],zones:[],selected:new Set(),publishTargets:new Set(),publishMode:'manual',publishGroup:'function:办公空间类',category:'all',zone:'全部',system:'全部',functionalGroup:'全部',query:'',activeDevice:null,simPower:'active'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escapeHTML=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const canOperate=()=>['admin','operator'].includes(state.user?.role), isAdmin=()=>state.user?.role==='admin';
const categoryMeta={all:['全部设备','ALL'],signage:['信息发布屏','SCREEN'],tv:['电视机','TV'],audio:['B&O 音响','B&O'],ops:['OPS 主机','OPS'],led:['LED 屏幕','LED']};
const capabilityLabels={verified:'已验证',pending_adapter:'待适配',unavailable:'不可用'};
const audioLabels={available:'已验证可播放',available_after_adapter:'硬件可播放 · 待适配',pending_verification:'扬声器待核验',unavailable:'不可播放'};
const loginForm=$('#loginForm');
const eventLabels={'device.profile_updated':'设备资料更新','device.location_updated':'空间位置更新','content.scene_created':'新增内容','content.scene_updated':'更新内容','content.deployed':'内容部署','content.deployment_restored':'部署恢复','player.play_scene':'场景发送','player.restore_state':'恢复原状态','player.set_power_mode':'模拟显示状态','player.set_volume':'模拟音量','player.set_input_source':'模拟输入源','visitor.entered_zone':'人员进入区域','sound.level_changed':'环境声级变化','camera.people_count':'人数变化'};

async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let data={};try{data=await response.json()}catch{}if(response.status===401&&!path.includes('/auth/'))showLogin();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2600)}
function showLogin(message=''){ $('#loginGate').hidden=false;$('#appShell').hidden=true;$('#loginError').textContent=message }
function showApp(){ $('#loginGate').hidden=true;$('#appShell').hidden=false;$('#userMenu').textContent=`${state.user.display_name} · ${state.user.role}${state.user.must_change_password?' · 需改密':''}`;$('#userManagement').hidden=!isAdmin() }

async function login(event){event.preventDefault();const form=new FormData(event.currentTarget);try{const result=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(form))});state.user=result.user;showApp();await loadData()}catch(error){showLogin(error.message)}}
async function logout(){await api('/api/v1/auth/logout',{method:'POST',body:'{}'});state.user=null;showLogin('已安全退出')}
async function changePassword(event){event.preventDefault();try{await api('/api/v1/auth/password',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});state.user.must_change_password=false;$('#passwordDialog').close();event.currentTarget.reset();toast('密码已修改，请妥善保存')}catch(error){toast(error.message)}}

async function loadData(){const data=await api('/api/v1/bootstrap');Object.assign(state,{devices:data.devices,scenes:data.scenes,events:data.events,deployments:data.deployments||[],zones:data.zones});renderAll(data);connectStream()}
function renderAll(data={safety:['真实设备输出锁定','控制适配器逐型号验收','不包含灯光与电机','所有资料修改均需登录']}){renderHeader();renderCategories();renderDimensions();renderDevices();renderLocations();renderPublishTargets();renderScenes();renderEvents();renderMap();renderSafety(data.safety);if(isAdmin())loadUsers()}
function renderHeader(){const verified=state.devices.filter(d=>d.address_verified).length;$('#deviceCount').textContent=state.devices.length;$('#verifiedCount').textContent=verified;$('#navDeviceCount').textContent=`${state.devices.length} 台`;$('#navPositionCount').textContent=`${state.devices.filter(d=>d.position_verified).length} 锚点`;$('#navSceneCount').textContent=`${state.scenes.length} 场景`;$('#navEventCount').textContent=`${state.events.length} 记录`}
function renderCategories(){const counts=Object.fromEntries(Object.keys(categoryMeta).map(key=>[key,0]));counts.all=state.devices.length;state.devices.forEach(d=>counts[d.category]=(counts[d.category]||0)+1);$('#categoryTabs').innerHTML=Object.entries(categoryMeta).map(([key,[label,code]])=>`<button class="category-tab ${state.category===key?'active':''}" data-category="${key}"><span>${code}</span><strong>${counts[key]||0}</strong><small>${label}</small></button>`).join('');$$('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderCategories();renderDimensions();renderDevices()})}
function systemFamily(d){const os=String(d.os_name||'');if(/windows/i.test(os))return 'Windows';if(/harmony/i.test(os))return 'HarmonyOS';if(/android/i.test(os))return 'Android';if(/B&O|Beolink/i.test(os))return 'B&O / Beolink';return '待核验'}
function functionalGroups(d){return String(d.functional_group||'未分组').split('/').map(value=>value.trim()).filter(Boolean)}
function dimensionButtons(selector,values,current,dataKey,allLabel){$(selector).innerHTML=[allLabel,...values].map(v=>`<button class="filter ${(current==='全部'&&v===allLabel)||current===v?'active':''}" data-${dataKey}="${escapeHTML(v)}">${escapeHTML(v)}</button>`).join('')}
function renderDimensions(){const base=state.category==='all'?state.devices:state.devices.filter(d=>d.category===state.category);const locations=[...new Set(base.map(d=>d.zone_id))].sort((a,b)=>a.localeCompare(b,'zh-CN'));const systems=[...new Set(base.map(systemFamily))].sort((a,b)=>a.localeCompare(b,'zh-CN'));const groups=[...new Set(base.flatMap(functionalGroups))].sort((a,b)=>a.localeCompare(b,'zh-CN'));if(state.zone!=='全部'&&!locations.includes(state.zone))state.zone='全部';if(state.system!=='全部'&&!systems.includes(state.system))state.system='全部';if(state.functionalGroup!=='全部'&&!groups.includes(state.functionalGroup))state.functionalGroup='全部';const locationSelect=$('#locationFilterSelect');locationSelect.innerHTML=['全部位置',...locations].map(value=>`<option value="${escapeHTML(value)}" ${value===(state.zone==='全部'?'全部位置':state.zone)?'selected':''}>${escapeHTML(value)}</option>`).join('');locationSelect.onchange=()=>{state.zone=locationSelect.value==='全部位置'?'全部':locationSelect.value;renderDevices()};dimensionButtons('#systemFilters',systems,state.system,'system','全部系统');dimensionButtons('#functionFilters',groups,state.functionalGroup,'function','全部功能组');$$('[data-system]').forEach(b=>b.onclick=()=>{state.system=b.dataset.system==='全部系统'?'全部':b.dataset.system;renderDimensions();renderDevices()});$$('[data-function]').forEach(b=>b.onclick=()=>{state.functionalGroup=b.dataset.function==='全部功能组'?'全部':b.dataset.function;renderDimensions();renderDevices()});$('#physicalLocations').innerHTML=state.zones.map(z=>`<option value="${escapeHTML(z)}">`).join('');$('#sensorZone').innerHTML=state.zones.map(z=>`<option>${escapeHTML(z)}</option>`).join('')}
function visibleDevices(){const q=state.query.trim().toLowerCase();return state.devices.filter(d=>(state.category==='all'||d.category===state.category)&&(state.zone==='全部'||d.zone_id===state.zone)&&(state.system==='全部'||systemFamily(d)===state.system)&&(state.functionalGroup==='全部'||functionalGroups(d).includes(state.functionalGroup))&&(!q||[d.name,d.address,d.mac_address,d.zone_id,d.functional_group,d.model,d.os_name].some(v=>String(v).toLowerCase().includes(q))))}
function renderDevices(){const devices=visibleDevices();$('#visibleDeviceCount').textContent=`${devices.length} 台设备`;$('#deviceGrid').innerHTML=devices.map(d=>`<article class="device-card ${state.selected.has(d.id)?'selected':''}" data-card="${d.id}"><header><label class="device-select"><input type="checkbox" data-select="${d.id}" ${state.selected.has(d.id)?'checked':''}><span></span></label><span class="verification ${d.address_verified?'verified':'pending'}">${d.address_verified?'IP 已核验':'IP 待核验'}</span></header><input class="inline-name" data-name="${d.id}" value="${escapeHTML(d.name)}" aria-label="编辑设备名称" ${canOperate()?'':'disabled'}><div class="device-meta"><b>${escapeHTML(d.model)}</b><span>${escapeHTML(d.os_name)} · ${escapeHTML(d.power_supply)}</span></div><strong class="device-ip">${escapeHTML(d.address||'IP 未录入')}</strong>${d.address&&!d.address_verified?'<small class="planned">规划地址</small>':''}<footer><span>${escapeHTML(d.zone_id)}</span><button data-manage="${d.id}">管理</button></footer></article>`).join('')||'<div class="empty-state"><strong>没有匹配设备</strong><span>请调整分类、空间或关键词</span></div>';$$('[data-select]').forEach(input=>input.onchange=()=>{input.checked?state.selected.add(input.dataset.select):state.selected.delete(input.dataset.select);renderDevices();renderSelection()});$$('[data-manage]').forEach(b=>b.onclick=()=>openDevice(b.dataset.manage));$$('[data-name]').forEach(input=>input.onchange=()=>saveInlineName(input.dataset.name,input.value));renderSelection()}
async function saveInlineName(id,name){const d=state.devices.find(x=>x.id===id);if(!d||name.trim()===d.name)return;try{const result=await api(`/api/v1/devices/${id}`,{method:'PUT',body:JSON.stringify(devicePayload(d,{name:name.trim()}))});replaceDevice(result.device);toast('设备名称已保存')}catch(error){toast(error.message);renderDevices()}}
function renderSelection(){const items=state.devices.filter(d=>state.selected.has(d.id));$('#selectedCount').textContent=`${items.length} 台`;$('#selectionSummary').innerHTML=items.length?`<p>${items.slice(0,3).map(d=>escapeHTML(d.name)).join('、')}${items.length>3?` 等 ${items.length} 台`:''}</p><small>${[...new Set(items.map(d=>categoryMeta[d.category][0]))].join(' · ')}</small>`:'<p>尚未选择设备</p><small>使用卡片左上角复选框多选</small>';const display=items.find(d=>d.category!=='audio');$('#openPlayer').href=display?`/player.html?device=${display.id}`:'#';$('#openPlayer').setAttribute('aria-disabled',String(!display))}

function devicePayload(d,override={}){return {name:d.name,locationName:d.zone_id,address:d.address,coordX:d.coord_x,coordY:d.coord_y,coordZ:d.coord_z,coordinateRef:d.coordinate_ref,positionVerified:d.position_verified,addressVerified:d.address_verified,audioStatus:d.audio_status,notes:d.notes,...override}}
function openDevice(id){const d=state.devices.find(x=>x.id===id);state.activeDevice=d;state.simPower=d.power_mode||'active';const f=$('#deviceForm');f.elements.deviceId.value=d.id;f.elements.name.value=d.name;f.elements.address.value=d.address;f.elements.locationName.value=d.zone_id;f.elements.coordX.value=d.coord_x??'';f.elements.coordY.value=d.coord_y??'';f.elements.coordZ.value=d.coord_z??'';f.elements.coordinateRef.value=d.coordinate_ref;f.elements.positionVerified.checked=d.position_verified;f.elements.addressVerified.checked=d.address_verified;f.elements.audioStatus.value=d.audio_status;f.elements.notes.value=d.notes;$('#deviceCategory').textContent=categoryMeta[d.category][0].toUpperCase();$('#deviceDialogTitle').textContent=d.name;$('#deviceEvidence').textContent=d.evidence;$('#deviceFacts').innerHTML=[['型号',d.model],['系统',d.os_name],['功能组',functionalGroups(d).join(' · ')],['供电',d.power_supply],['分辨率',d.resolution],['MAC',d.mac_address||'待录入'],['网络模式',(d.network_mode||'待核验').toUpperCase()],['子网掩码',d.subnet_mask||'待核验'],['网关',d.gateway||'待核验'],['DNS',(d.dns_servers||[]).join(' / ')||'待核验'],['适配器',d.adapter]].map(([k,v])=>`<p><span>${k}</span><b>${escapeHTML(v)}</b></p>`).join('');$('#controlCapabilities').innerHTML=Object.entries(d.control_status).map(([key,value])=>`<p><span>${{power:'软件开关',volume:'音量',source:'输入源'}[key]}</span><b class="cap-status ${value}">${capabilityLabels[value]||value}</b></p>`).join('')+`<p><span>屏幕声音</span><b>${audioLabels[d.audio_status]}</b></p>`;$('#deviceVolume').value=d.volume;$('#deviceVolumeLabel').textContent=`${d.volume}%`;$('#deviceInputSource').innerHTML=d.input_sources.map(s=>`<option ${s===d.input_source?'selected':''}>${escapeHTML(s)}</option>`).join('');$$('[data-sim-power]').forEach(b=>b.classList.toggle('active',b.dataset.simPower===state.simPower));f.querySelectorAll('input,select,textarea,button[type=submit]').forEach(el=>el.disabled=!canOperate());$('#deviceDialog').showModal()}
async function saveDevice(event){event.preventDefault();const f=event.currentTarget,d=state.activeDevice;const p=devicePayload(d,{name:f.elements.name.value.trim(),address:f.elements.address.value.trim(),locationName:f.elements.locationName.value.trim(),coordX:f.elements.coordX.value,coordY:f.elements.coordY.value,coordZ:f.elements.coordZ.value,coordinateRef:f.elements.coordinateRef.value.trim(),positionVerified:f.elements.positionVerified.checked,addressVerified:f.elements.addressVerified.checked,audioStatus:f.elements.audioStatus.value,notes:f.elements.notes.value});try{const result=await api(`/api/v1/devices/${d.id}`,{method:'PUT',body:JSON.stringify(p)});replaceDevice(result.device);$('#deviceDialog').close();renderAll();toast('设备资料与 BaiField 坐标已保存')}catch(error){toast(error.message)}}
function replaceDevice(device){const i=state.devices.findIndex(d=>d.id===device.id);state.devices[i]=device;state.zones=[...new Set(state.devices.map(d=>d.zone_id))].sort((a,b)=>a.localeCompare(b,'zh-CN'));state.activeDevice=device}
async function simulateControl(){const d=state.activeDevice;if(!d)return;if(!canOperate())return toast('当前账号为只读权限');const volume=Number($('#deviceVolume').value),source=$('#deviceInputSource').value;try{await api('/api/v1/commands',{method:'POST',body:JSON.stringify({type:'set_power_mode',targets:[d.id],powerMode:state.simPower,source:'operator'})});await api('/api/v1/commands',{method:'POST',body:JSON.stringify({type:'set_volume',targets:[d.id],volume,source:'operator'})});await api('/api/v1/commands',{method:'POST',body:JSON.stringify({type:'set_input_source',targets:[d.id],inputSource:source,source:'operator'})});Object.assign(d,{power_mode:state.simPower,volume,input_source:source});toast('已记录模拟状态；未向真实设备发送指令')}catch(error){toast(error.message)}}

function renderLocations(){const items=state.devices.filter(d=>d.category!=='audio'||d.address);if($('#coordinateDeviceCount'))$('#coordinateDeviceCount').textContent=`${items.length} 台设备`;$('#locationList').innerHTML=items.map(d=>`<article class="location-row"><div><strong>${escapeHTML(d.name)}</strong><small class="location-ip">${escapeHTML(d.address||'IP 未录入')}</small><small>${escapeHTML(d.zone_id)}</small></div><div class="coordinate-readout"><span>X <b>${d.coord_x??'—'}</b></span><span>Y <b>${d.coord_y??'—'}</b></span><span>Z <b>${d.coord_z??'—'}</b></span><em class="${d.position_verified?'verified':'pending'}">${d.position_verified?'已核验锚点':'待现场测量'}</em></div><div><span class="audio-state">${audioLabels[d.audio_status]}</span><button data-manage="${d.id}">编辑坐标</button></div></article>`).join('');$$('#locationList [data-manage]').forEach(b=>b.onclick=()=>openDevice(b.dataset.manage))}
function renderMap(){const map=$('#spatialMap');map.querySelectorAll('.device-pin').forEach(n=>n.remove());state.devices.filter(d=>d.position_verified&&d.coord_x!=null&&d.coord_y!=null).forEach(d=>{const pin=document.createElement('button');pin.className=`device-pin ${d.category}`;pin.style.left=`${Math.max(4,Math.min(94,Number(d.coord_x)))}%`;pin.style.top=`${Math.max(5,Math.min(92,Number(d.coord_y)))}%`;pin.title=d.name;pin.textContent=categoryMeta[d.category][1];pin.onclick=()=>openDevice(d.id);map.append(pin)})}

function publishableDevices(){return state.devices.filter(d=>d.category!=='audio'&&['image','video','web'].some(cap=>d.capabilities.includes(cap)))}
function publishGroupOptions(){const devices=publishableDevices(),options=[];[...new Set(devices.flatMap(functionalGroups))].sort((a,b)=>a.localeCompare(b,'zh-CN')).forEach(value=>options.push({value:`function:${value}`,label:`功能组 · ${value}`}));[...new Set(devices.map(d=>d.zone_id||'未分组'))].sort((a,b)=>a.localeCompare(b,'zh-CN')).forEach(value=>options.push({value:`location:${value}`,label:`位置 · ${value}`}));[...new Set(devices.map(systemFamily))].sort((a,b)=>a.localeCompare(b,'zh-CN')).forEach(value=>options.push({value:`system:${value}`,label:`系统 · ${value}`}));return options}
function currentPublishDevices(){const devices=publishableDevices();if(state.publishMode==='manual')return devices.filter(d=>state.publishTargets.has(d.id));const [type,...rest]=state.publishGroup.split(':'),value=rest.join(':');return devices.filter(d=>type==='function'?functionalGroups(d).includes(value):type==='location'?d.zone_id===value:systemFamily(d)===value)}
function deploymentLabel(item){if(!item)return '尚未部署';const scene=state.scenes.find(s=>s.id===item.scene_id);const status={prepared:'准备中',simulated:'流程已执行 · 等待真实适配器',dispatched:'已发送 · 等待终端回执',failed:'部署失败',restored:'已恢复原状态'}[item.status]||item.status;return `${scene?.name||item.scene_id} · ${item.targets.length} 台 · ${status}`}
function renderPublishTargets(){if(!$('#publishTargets'))return;const devices=publishableDevices(),options=publishGroupOptions();if(!options.some(item=>item.value===state.publishGroup))state.publishGroup=options[0]?.value||'';$('#publishGroup').innerHTML=options.map(item=>`<option value="${escapeHTML(item.value)}" ${item.value===state.publishGroup?'selected':''}>${escapeHTML(item.label)}</option>`).join('');$('#publishGroupLabel').hidden=state.publishMode!=='group';$$('[data-publish-mode]').forEach(b=>b.classList.toggle('active',b.dataset.publishMode===state.publishMode));const targets=currentPublishDevices();$('#publishTargetCount').textContent=`${targets.length} 台目标`;const latest=state.deployments[0];$('#deploymentStatus').textContent=deploymentLabel(latest);$('#restoreLastDeployment').disabled=!latest||Boolean(latest.restored_at)||!canOperate();if(state.publishMode==='manual'){$('#publishTargets').innerHTML=devices.map(d=>`<label class="publish-target ${state.publishTargets.has(d.id)?'selected':''}"><input type="checkbox" data-publish-target="${d.id}" ${state.publishTargets.has(d.id)?'checked':''}><span><strong>${escapeHTML(d.name)}</strong><small>${escapeHTML(d.zone_id)} · ${escapeHTML(systemFamily(d))}</small></span></label>`).join('');$$('[data-publish-target]').forEach(input=>input.onchange=()=>{input.checked?state.publishTargets.add(input.dataset.publishTarget):state.publishTargets.delete(input.dataset.publishTarget);renderPublishTargets();renderScenes()})}else{$('#publishTargets').innerHTML=targets.map(d=>`<article class="publish-target selected"><span><strong>${escapeHTML(d.name)}</strong><small>${escapeHTML(d.zone_id)} · ${escapeHTML(systemFamily(d))}</small></span></article>`).join('')||'<p class="publish-empty">当前整组没有可发布设备</p>'}}
function renderScenes(){const count=currentPublishDevices().length;$('#sceneList').innerHTML=state.scenes.map(s=>`<article class="scene-card" style="--accent:${escapeHTML(s.accent)}"><div><h3>${escapeHTML(s.name)}</h3><p>${escapeHTML(s.title)}</p><code>${escapeHTML(s.kind.toUpperCase())}</code></div><div class="scene-actions"><button data-edit-scene="${s.id}">编辑</button><button data-publish="${s.id}" ${count&&canOperate()?'':'disabled'}>发送部署 · ${count} 台</button></div></article>`).join('');$$('[data-edit-scene]').forEach(b=>b.onclick=()=>openScene(b.dataset.editScene));$$('[data-publish]').forEach(b=>b.onclick=()=>publishScene(b.dataset.publish))}
function openScene(id=''){const s=state.scenes.find(x=>x.id===id),f=$('#sceneForm');f.reset();f.elements.originalId.value=s?.id||'';if(s)Object.entries({name:s.name,id:s.id,title:s.title,subtitle:s.subtitle,kind:s.kind,accent:s.accent,mediaUrl:s.media_url,duration:s.duration}).forEach(([k,v])=>f.elements[k].value=v);$('#sceneDialog').showModal()}
async function saveScene(event){event.preventDefault();const p=Object.fromEntries(new FormData(event.currentTarget)),id=p.originalId;delete p.originalId;p.duration=Number(p.duration||0);try{const result=await api(id?`/api/v1/scenes/${id}`:'/api/v1/scenes',{method:id?'PUT':'POST',body:JSON.stringify(p)});if(id)state.scenes[state.scenes.findIndex(s=>s.id===id)]=result.scene;else state.scenes.push(result.scene);$('#sceneDialog').close();renderScenes();toast('内容场景已保存')}catch(error){toast(error.message)}}
async function publishScene(sceneId){const devices=currentPublishDevices();if(!devices.length)return toast('请先选择至少一台设备或一个整组');if(!confirm(`将“${state.scenes.find(s=>s.id===sceneId)?.name||sceneId}”部署到 ${devices.length} 台设备，并保存可恢复快照。继续？`))return;try{const result=await api('/api/v1/deployments',{method:'POST',body:JSON.stringify({sceneId,targets:devices.map(d=>d.id),targetGroup:state.publishMode==='group'?state.publishGroup:'手动选择'})});state.deployments.unshift(result.deployment);devices.forEach(d=>d.current_scene=sceneId);renderPublishTargets();renderScenes();toast('部署流程已执行；真实终端仍等待适配器回执')}catch(error){toast(error.message)}}
async function restoreLastDeployment(){const deployment=state.deployments[0];if(!deployment||deployment.restored_at)return;if(!confirm(`恢复本次部署涉及的 ${deployment.targets.length} 台设备到发送前状态？`))return;try{const result=await api(`/api/v1/deployments/${deployment.id}/restore`,{method:'POST',body:'{}'});state.deployments[0]=result.deployment;result.devices.forEach(replaceDevice);renderPublishTargets();renderScenes();renderDevices();toast('已恢复到本次部署前保存的状态')}catch(error){toast(error.message)}}

function renderEvents(){const q=$('#eventSearch')?.value.toLowerCase()||'';const rows=state.events.filter(e=>!q||JSON.stringify(e).toLowerCase().includes(q));$('#eventRows').innerHTML=rows.map(e=>`<tr><td>${new Date(e.occurred_at).toLocaleString('zh-CN')}</td><td>${escapeHTML(e.source)}</td><td><strong>${escapeHTML(eventLabels[e.event_type]||e.event_type)}</strong><small>${escapeHTML(e.event_type)}</small></td><td>${escapeHTML(e.zone_id||e.subject_id||'—')}</td><td><span class="result-chip">${escapeHTML(e.result)}</span></td></tr>`).join('')}
async function refreshEvents(){const d=await api('/api/v1/events?limit=100');state.events=d.items;renderEvents();toast('运行记录已刷新')}
async function submitField(event){event.preventDefault();try{const r=await api('/api/v1/field/events',{method:'POST',body:JSON.stringify({source:'BaiField',eventType:$('#sensorEvent').value,zoneId:$('#sensorZone').value,subjectId:'UWB-017',confidence:Number($('#confidence').value)/100,payload:{peopleCount:1}})});state.events.unshift(r.event);renderEvents();toast(r.command?'已触发模拟场景':'事件已记录，未触发设备')}catch(error){toast(error.message)}}

async function loadUsers(){try{const d=await api('/api/v1/users');$('#userList').innerHTML=d.items.map(u=>`<article><div><strong>${escapeHTML(u.display_name)}</strong><small>@${escapeHTML(u.username)}</small></div><span class="role ${u.role}">${u.role}</span><span>${u.enabled?'已启用':'已停用'}</span><small>${u.must_change_password?'需修改初始密码':'密码已设置'}</small></article>`).join('')}catch(error){toast(error.message)}}
async function createUser(event){event.preventDefault();try{await api('/api/v1/users',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});$('#userDialog').close();event.currentTarget.reset();loadUsers();toast('用户已创建')}catch(error){toast(error.message)}}
function renderSafety(items){$('#safetyList').innerHTML=items.map(i=>`<li>${escapeHTML(i)}</li>`).join('')}
function connectStream(){if(state.stream)state.stream.close();state.stream=new EventSource('/api/v1/stream?channel=dashboard');state.stream.addEventListener('ready',()=>$('#streamState').textContent='实时');state.stream.onerror=()=>$('#streamState').textContent='重连中'}

function activateView(view){$$('.mode-nav button').forEach(button=>{const active=button.dataset.view===view;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});$$('.view').forEach(node=>node.classList.toggle('active',node.id===`view-${view}`));$('#userDropdown').hidden=true;$('#userMenu').setAttribute('aria-expanded','false');if(view==='users'&&isAdmin())loadUsers();if(view==='field'){renderMap();renderLocations()}if(view==='scenes'){renderPublishTargets();renderScenes()}}

function bindUI(){loginForm.addEventListener('submit',login);$('#logout').onclick=logout;$('#userMenu').onclick=()=>{const menu=$('#userDropdown'),open=menu.hidden;menu.hidden=!open;$('#userMenu').setAttribute('aria-expanded',String(open))};$('#userManagement').onclick=()=>activateView('users');$('#changeMyPassword').onclick=()=>{$('#userDropdown').hidden=true;$('#userMenu').setAttribute('aria-expanded','false');$('#passwordDialog').showModal()};document.addEventListener('click',event=>{if(!event.target.closest('.user-menu-wrap')){$('#userDropdown').hidden=true;$('#userMenu').setAttribute('aria-expanded','false')}});$('#deviceSearch').oninput=e=>{state.query=e.target.value;renderDevices()};$('#selectVisible').onclick=()=>{visibleDevices().forEach(d=>state.selected.add(d.id));renderDevices()};$('#clearSelection').onclick=()=>{state.selected.clear();renderDevices()};$('#deviceForm').onsubmit=saveDevice;$('#sceneForm').onsubmit=saveScene;$('#userForm').onsubmit=createUser;$('#addScene').onclick=()=>openScene();$('#addUser').onclick=()=>$('#userDialog').showModal();$('#refreshEvents').onclick=refreshEvents;$('#eventSearch').oninput=renderEvents;$('#sensorForm').onsubmit=submitField;$('#confidence').oninput=e=>$('#confidenceValue').textContent=`${e.target.value}%`;$('#deviceVolume').oninput=e=>$('#deviceVolumeLabel').textContent=`${e.target.value}%`;$('#simulateControl').onclick=simulateControl;$$('[data-publish-mode]').forEach(b=>b.onclick=()=>{state.publishMode=b.dataset.publishMode;renderPublishTargets();renderScenes()});$('#publishGroup').onchange=e=>{state.publishGroup=e.target.value;renderPublishTargets();renderScenes()};$('#useDeviceSelection').onclick=()=>{state.publishMode='manual';state.publishTargets=new Set([...state.selected].filter(id=>publishableDevices().some(d=>d.id===id)));renderPublishTargets();renderScenes();toast(state.publishTargets.size?'已载入设备页选择':'设备页尚未选择可发布终端')};$('#restoreLastDeployment').onclick=restoreLastDeployment;$$('[data-sim-power]').forEach(b=>b.onclick=()=>{state.simPower=b.dataset.simPower;$$('[data-sim-power]').forEach(x=>x.classList.toggle('active',x===b))});$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());$$('.mode-nav button').forEach(b=>b.onclick=()=>activateView(b.dataset.view))}
async function boot(){bindUI();setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false}),1000);try{const auth=await api('/api/v1/auth/status');if(!auth.authenticated)return showLogin();state.user=auth.user;showApp();await loadData()}catch(error){showLogin(error.message)}}
$('#passwordForm').onsubmit=changePassword;
boot();
