const params=new URLSearchParams(location.search);const deviceId=params.get('device')||localStorage.getItem('baiplayer.deviceId')||`web-${Math.random().toString(16).slice(2,8)}`;localStorage.setItem('baiplayer.deviceId',deviceId);let scenes=[];let device=null;const $=s=>document.querySelector(s);
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json()}
function applyScene(id){const scene=scenes.find(item=>item.id===id)||scenes[0];if(!scene)return;document.documentElement.style.setProperty('--accent',scene.accent);$('#sceneKind').textContent=scene.kind.toUpperCase();$('#sceneTitle').textContent=scene.title;$('#sceneSubtitle').textContent=scene.subtitle;$('#sceneId').textContent=`SCENE · ${scene.id.toUpperCase()}`;renderMedia(scene);localStorage.setItem('baiplayer.lastScene',JSON.stringify(scene));heartbeat(scene.id)}
function renderMedia(scene){const layer=$('#mediaLayer');layer.innerHTML='';if(!scene.media_url)return;const video=/\.(mp4|webm)$/i.test(scene.media_url);const media=document.createElement(video?'video':'img');media.src=scene.media_url;if(video){media.autoplay=true;media.loop=true;media.muted=false;media.playsInline=true}layer.append(media)}
async function heartbeat(sceneId=''){try{await api('/api/v1/devices/heartbeat',{method:'POST',body:JSON.stringify({deviceId,sceneId})})}catch{}}
async function boot(){try{const data=await api('/api/v1/bootstrap');localStorage.setItem('baiplayer.bootstrap',JSON.stringify(data));scenes=data.scenes;device=data.devices.find(item=>item.id===deviceId);if(!device){const result=await api('/api/v1/devices/register',{method:'POST',body:JSON.stringify({deviceId,name:`BaiPlayer ${deviceId}`,type:'web',zoneId:'未分区',capabilities:['image','video','audio','web']})});device=result.device}renderDevice(data.mode);applyScene(device.current_scene);connect();setInterval(()=>heartbeat(),15000)}catch(error){const cached=JSON.parse(localStorage.getItem('baiplayer.bootstrap')||'null');const lastScene=JSON.parse(localStorage.getItem('baiplayer.lastScene')||'null');if(cached){scenes=cached.scenes;device=cached.devices.find(item=>item.id===deviceId);renderDevice('OFFLINE CACHE');applyScene(lastScene?.id||device?.current_scene||'ambient')}$('#connection').textContent=`离线播放 · ${error.message}`}}
function renderDevice(mode){if(!device)return;$('#deviceName').textContent=device.name.toUpperCase();$('#zoneName').textContent=device.zone_id;$('#runtimeMode').textContent=mode;setPowerMode(device.power_mode||localStorage.getItem('baiplayer.powerMode')||'active')}
function setPowerMode(mode){$('#stage').dataset.power=mode;localStorage.setItem('baiplayer.powerMode',mode);$('#unlock')?.classList.toggle('power-hidden',mode==='standby');if(mode==='standby')document.querySelectorAll('video,audio').forEach(media=>media.pause());if(mode==='active')document.querySelectorAll('video,audio').forEach(media=>media.play().catch(()=>{}))}
function connect(){const stream=new EventSource(`/api/v1/stream?deviceId=${encodeURIComponent(deviceId)}`);stream.addEventListener('ready',()=>$('#connection').textContent='AOS母机在线 · 实时事件通道');stream.addEventListener('command',event=>{const command=JSON.parse(event.data);if(command.command_type==='play_scene')applyScene(command.scene_id);if(command.command_type==='set_power_mode')setPowerMode(command.power_mode);if(command.command_type==='set_volume'){const media=document.querySelector('video,audio');if(media)media.volume=command.volume/100}if(command.command_type==='restore_state'){const previous=(command.state_map||[]).find(item=>item.deviceId===deviceId);if(previous){applyScene(previous.currentScene);setPowerMode(previous.powerMode);const media=document.querySelector('video,audio');if(media)media.volume=previous.volume/100}}api('/api/v1/commands/ack',{method:'POST',body:JSON.stringify({commandId:command.id,deviceId,status:'playing'})}).catch(()=>{})});stream.onerror=()=>$('#connection').textContent='连接中断 · 正在自动重连'}
$('#unlock button').addEventListener('click',()=>{document.querySelectorAll('video,audio').forEach(media=>media.play().catch(()=>{}));$('#unlock').classList.add('hidden')});if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});boot();
