/* Shared display logic for the APK and the browser preview. All traces contain received samples. */
(function(){
'use strict';
var query=new URLSearchParams(location.search),mode=query.get('mode')||'pulse',camera=query.get('camera')||(mode==='pulse'?'D1':'D4');
var titles=['空间总览','网络','认知声学','视觉算力','感知设备','空间状态'];
var page=Math.max(0,Math.min(5,Number(query.get('page'))||0)),fixed=query.has('page')||mode!=='pulse',vision=null,network=null,received=0,networkReceived=0,error='',networkError='',history=[],lastFrame=null;
var content=document.getElementById('content'),nav=document.getElementById('nav');
var lastRenderKey='',lastInteraction=0,nextPage=Date.now()+18000,sourceClockOffset=0;
var acoustics=null;
var labels={P01:'响应张量',P02:'衰减剖面',P03:'直达混响',P04:'系统传递',S01:'声源场',S02:'扩散性',S03:'包围感',S04:'空间分离',T01:'事件密度',T02:'节奏结构',T03:'持续性',T04:'转移不确定性',M01:'事件身份',M02:'语义显著',M03:'关系落地',M04:'异常歧义',H01:'聆听努力',H02:'注意对齐',H03:'愉悦活跃',H04:'隐私自主',A01:'响应可供',A02:'响应置信',A03:'代价可逆',A04:'结果增量'};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(x){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x];});}
function num(v){return typeof v==='number'&&Number.isFinite(v)?v:null;}
function fmt(v,d,unit){return num(v)===null?'暂未接入':v.toFixed(d||0)+(unit||'');}
function ageSeconds(){if(!vision)return Infinity;var t=num((vision.frame||{}).timestamp);return t===null?Infinity:(Date.now()/1000-t);}
function cameraData(){return ((vision||{}).multi_camera_monitor||{}).cameras?.find(function(x){return x.camera_code===camera;})||null;}
function cameraAge(c,type){if(!c)return Infinity;var base=ageSeconds();if(base < -5)return Infinity;var a=num(c[type+'_age_seconds']);return a===null?Infinity:Math.max(0,base)+a;}
function liveCamera(c,type){return !!c&&!error&&((vision||{}).multi_camera_monitor||{}).enabled===true&&c[type==='detection'?'video_state':'audio_state']==='live'&&c[type+'_stale']===false&&cameraAge(c,type)<=5;}
function people(c){return liveCamera(c,'detection')?num(c.person_count):null;}
function sound(c){return liveCamera(c,'audio')?num(c.dbfs):null;}
function localSemantic(){return ((vision||{}).multimodal_perception||{}).results?.find(function(x){return x.camera_code===camera;})||null;}
function semanticFresh(s){var a=s?Date.now()/1000-num(s.timestamp):Infinity,domain=s?.domains?.spatial_attribute,t=num(domain?.updated_at),da=t===null?Infinity:Date.now()/1000-t;return !!s&&visionFresh()&&s.stale===false&&num(s.timestamp)!==null&&a>=-5&&a<=120&&da>=-5&&da<=120&&typeof domain?.label==='string'&&domain.label.length>0;}
function visionFresh(){return !!vision&&!error&&ageSeconds()>=-5&&ageSeconds()<=5;}
function networkFresh(){return !!network&&!networkError&&Date.now()-networkReceived<=45000&&Date.now()/1000-num(network.timestamp)<=45&&Date.now()/1000-num(network.timestamp)>=-5&&num(network.timestamp)!==null;}
function metric(label,value,hint){return '<div class="metric"><label>'+esc(label)+'</label><strong>'+esc(value)+'</strong><em>'+esc(hint||'')+'</em></div>';}
function state(live,label){return '<div class="state '+(live?'live':'')+'"><i></i>'+esc(label)+'</div>';}
function trace(key,large){var samples=history.slice(-90),now=Date.now(),values=samples.filter(function(s){return num(s[key])!==null;}).map(function(s){return s[key];});var mn=values.length?Math.min.apply(null,values):0,mx=values.length?Math.max.apply(null,values):1;if(mx-mn<1){mn-=.5;mx+=.5;}var path='',prev=null;samples.forEach(function(s){if(num(s[key])===null){prev=null;return;}var x=1000-((now-s.at)/180000)*1000,y=80-((s[key]-mn)/(mx-mn))*66;if(x<0)return;path+=(prev!==null&&s.at-prev<=6000?'L':'M')+x.toFixed(1)+','+y.toFixed(1);prev=s.at;});return '<svg class="trace '+(large?'large-chart':'')+'" viewBox="0 0 1000 94" preserveAspectRatio="none" aria-label="最近三分钟的实际采样趋势"><line x1="0" y1="84" x2="1000" y2="84"/><path d="'+path+'"/></svg><div class="timeline-labels"><span>−3 分钟 · 接收后开始记录</span><span>'+esc(values.length?fmt(mn,1)+' — '+fmt(mx,1):'等待真实采样')+' · 当前</span></div>';}
function acousticSource(){return acoustics?.sources?.find(function(s){return s.id==='microphone-1'&&s.spaceId==='future_scene';})||null;}
function acousticFresh(){var t=Date.parse(acoustics?.dataCollectedAt||''),a=(Date.now()-t)/1000;return acoustics?.transport?.status==='OK'&&a>=-5&&a<=12;}
function acousticValue(id){var s=acousticSource(),p=s?.parameters?.find(function(p){return p.id===id;});if(!p||!p.present)return '待接入';if(!acousticFresh()||s.connection!=='CONNECTED')return '来源离线 / 过期';var ends=(p.windows||[]).map(function(w){return Date.parse(w.end);}),age=ends.length?(Date.now()-Math.min.apply(null,ends))/1000:Infinity;if(!Number.isFinite(age)||age< -5||age>180)return '采样过期';if(!p.available||p.carriedForward)return p.carriedForward?'历史估计 · 不作实时值':'证据不足 / 未检出';return p.value||'无有效值';}
function sca(){var f=['物理','空间','时间','意义','人因','响应'],ids=['P','S','T','M','H','A'];return '<div class="sca">'+ids.map(function(g,i){return '<div class="sca-group">'+f[i]+[1,2,3,4].map(function(n){var id=g+'0'+n,status=(g==='P'||(g==='S'&&n<3))?'待校准':g==='H'?'待人因证据':'待模型接入';return '<div class="sca-cell"><b>'+id+' '+labels[id]+'</b><span>'+esc(acousticValue(id))+'</span></div>';}).join('')+'</div>';}).join('')+'</div>';}
function gpu(){var g=((vision||{}).metrics||{}).gpu_memory_by_device||[];return '<div class="server-gpu">'+g.map(function(x){var used=num(x.used_mb),total=num(x.total_mb),ok=visionFresh()&&used!==null&&total>0;return '<div class="gpu"><small>GPU '+esc(x.gpu_id)+' · 显存</small><strong>'+ (ok?fmt(used/1024,1)+' / '+fmt(total/1024,1)+' GiB':'等待数据')+'</strong><div class="bar"><span style="width:'+(ok?Math.max(0,Math.min(100,100*used/total)):0)+'%"></span></div></div>';}).join('')+'</div>';}
function algorithms(){var a=(vision||{}).algorithms||{},names={detection:'目标检测',face_detection:'人脸检测',depth:'相对深度',head_pose:'头部姿态',speech_recognition:'语音识别',audio_perception:'声音理解'};return '<div class="chips">'+Object.keys(names).map(function(k){var x=a[k]||{},top=(vision||{})[k],label=x.enabled===false?'未开启':!visionFresh()?'等待数据':top&&top.ready!==x.ready?'状态不一致':x.ready===true?'就绪':'等待输入';return '<span class="chip">'+names[k]+' · '+label+'</span>';}).join('')+'</div>';}
function cameras(){var all=((vision||{}).multi_camera_monitor||{}).cameras||[];return '<div class="data-grid">'+all.map(function(c){var p=people(c),a=sound(c),own=c.person_count_source_camera_code===c.camera_code;return '<div class="datum"><b>'+esc(c.camera_code+' '+c.location_name)+'</b><small class="'+(p!==null?'live':'')+'">'+(p!==null?p+' 人估计':'人数未知')+' · '+(a!==null?fmt(a,1)+' dBFS':'音频未知')+(own?'':' · 人数源 '+esc(c.person_count_source_camera_code||'未知'))+'</small></div>';}).join('')+'</div>';}
function semanticBlock(){var s=localSemantic(),fresh=semanticFresh(s),label=s?.domains?.spatial_attribute?.label,score=num(s?.domains?.spatial_attribute?.score);return '<div class="semantic"><span class="semantic-label">'+esc(fresh&&label?label:s?'理解结果已过期':'等待空间理解')+'</span><small>'+esc(s?'D'+s.channel+' · '+s.location_name+' · '+Math.max(0,Math.round(Date.now()/1000-s.timestamp))+' 秒前':'临近摄像头尚未提供语义结果')+(fresh&&score!==null?' · 模型原始得分 '+fmt(score,3):'')+'</small></div><p class="note">模型输出是一种推断。原始得分未校准为正确概率；过期结果不参与当前空间判断。</p>';}
function home(){var c=cameraData(),p=people(c),a=sound(c),all=((vision||{}).multi_camera_monitor||{}).cameras||[],ready=all.filter(function(x){return liveCamera(x,'detection');}).length;return '<div><div class="eyebrow">SPACE VITALS</div><div class="chapter">空间生命体征</div><h1>让空间理解此刻</h1><p class="lead">声音、视觉与计算共同表达空间的变化。<br>每一个数值，都保留它的来源与时间。</p><div class="hero-value">'+(p===null?'—':p)+'<span>人 · 视觉估计</span></div>'+state(p!==null,p!==null?c.location_name+' · '+camera+' · 实时人数':camera+' · 等待实时感知')+trace('sound',false)+'<p class="note">临近摄像头音频 '+(a===null?'暂未接入':fmt(a,1)+' dBFS')+' · 未校准为声压级。人数为模型估计。</p></div><aside class="rail"><div class="eyebrow">SYSTEM PULSE</div><div class="chapter">系统脉搏</div>'+metric('视觉感知 / VISION',ready+' / '+all.length,'实时通道')+metric('认知声学 / COGNITIVE ACOUSTICS','S/CA–24','研发声学源 · 24 项逐项核验')+metric('视觉计算 / INFERENCE',visionFresh()?fmt(vision.metrics?.infer_ms,1,' ms'):'等待数据','服务器瞬时耗时')+metric('本地声能 / LOCAL AUDIO',a===null?'等待数据':fmt(a,1,' dBFS'),'数字声能 · 未校准')+metric('网络 / NETWORK',networkFresh()?'实时接入':'等待数据','独立于视觉链路')+'</aside>';}
function detail(){var c=cameraData(),p=people(c),a=sound(c),v=visionFresh(),m=(vision||{}).metrics||{},nf=networkFresh();var en=['','NETWORK NOW','COGNITIVE ACOUSTICS','VISION COMPUTE','SENSING NODES','SPACE NOW'],heads=['','网络正在流动','从声音走向理解','感知在后台运行','设备构成空间触点','空间正在被观察'];var leads=['','保留原来的网络监测链路，独立呈现带宽与连接状态。','从可测的声能出发，把声学证据、意义与人的体验连接起来。','画面采集、模型推理与双 GPU 显存，呈现真实运行的计算过程。','每一个通道都有自己的位置、更新时间与状态。','临近摄像头提供人数与声音，空间语义保留模型的边界。'];var extra='',rail='',good=false;
 if(page===1){good=nf;rail=metric('WAN 下载',nf?fmt(network.wan_down_mbps,1,' Mbps'):'等待数据')+metric('WAN 上传',nf?fmt(network.wan_up_mbps,1,' Mbps'):'等待数据')+metric('在线接口',nf?fmt(network.online_interfaces):'等待数据')+metric('活动会话',nf?fmt(network.active_sessions):'等待数据');extra='<div class="pipeline"><span>SNMP</span><b>→</b><span>Prometheus</span><b>→</b><span>Health API</span></div><p class="note">监测评分仅描述网络链路。终端数与会话数没有源指标时不显示数值。</p>';}
 if(page===2){good=a!==null;extra=trace('sound',false)+sca()+'<p class="note">S/CA–24 研发数据来自未来场景 · 麦克风 1，不代表本空间。180 秒以上及历史沿用值不作实时值；人因项是模型代理，非主观实测。</p>';rail=metric('临近摄像头声能',a===null?'等待数据':fmt(a,1,' dBFS'),camera+' · 数字满刻度参考')+metric('声压级 / SPL','待校准','需要声学校准链')+metric('声学认知参数','24 / 24','保留全部研究维度')+metric('研发源 · 事件密度',acousticValue('T01'),'未来场景麦克风 1 · 非本地');}
 if(page===3){good=v;extra=gpu()+algorithms()+'<p class="note">显存用量与推理耗时为服务器遥测；不能由显存推算 GPU 利用率。此页为整体服务，非单路摄像头性能。</p>';rail=metric('推理吞吐',v?fmt(m.fps,1,' FPS'):'等待数据')+metric('推理耗时',v?fmt(m.infer_ms,1,' ms'):'等待数据')+metric('采集滞后',v?fmt(m.camera_lag_ms,0,' ms'):'等待数据')+metric('GPU 利用率','暂未接入','接口没有提供该指标');}
 if(page===4){var all=((vision||{}).multi_camera_monitor||{}).cameras||[],active=all.filter(function(x){return liveCamera(x,'detection');}).length;good=v;extra=cameras()+'<p class="note">各区域独立显示。D16 人数当前引用 D6，不能把所有通道人数直接相加成楼层人数。</p>';rail=metric('视觉检测通道',active+' / '+all.length,'检测时间 ≤ 5 秒')+metric('音频通道',all.filter(function(x){return liveCamera(x,'audio');}).length+' / '+all.length,'音频时间 ≤ 5 秒')+metric('本机展示模式',mode==='pulse'?'六页轮播':'全景 '+mode.replace('panorama',''),'界面运行不等于电视在线验收')+metric('电视播放回执','待设备验收','需核对前台与启动状态');}
 if(page===5){good=p!==null;extra=semanticBlock()+trace('people',false)+'<p class="note">温度、湿度与空气质量尚无传感器证据。视觉占用估计不替代门禁或安防判断。</p>';rail=metric('本空间人数',p===null?'未知':fmt(p)+' 人',camera+' · 视觉估计')+metric('本空间声能',a===null?'未知':fmt(a,1,' dBFS'),'未校准')+metric('语义理解',semanticFresh(localSemantic())?'模型结果可用':'等待新结果','逐字段判断新鲜度')+metric('环境传感器','暂未接入','温度 · 湿度 · 空气质量');}
 return '<div><div class="eyebrow">'+en[page]+'</div><div class="chapter">'+titles[page]+'</div><h1>'+heads[page]+'</h1><p class="lead">'+leads[page]+'</p>'+state(good,good?'实时来源已连接':'等待有效数据 · 未接入项保持未知')+extra+'</div><aside class="rail"><div class="eyebrow">TRACEABLE SIGNAL</div><div class="chapter">来源可追溯</div>'+rail+'</aside>';}
function panorama(){var n=Number(mode.replace('panorama',''))||1,c=cameraData(),p=people(c),a=sound(c),good=n===1?p!==null:n===2?semanticFresh(localSemantic()):visionFresh(),left='',rail='';if(n===1){left='<h1>空间持续呼吸</h1><p class="lead">把连续的空间感，连接到此刻真实发生的变化。</p><div class="hero-value">'+(p===null?'—':p)+'<span>人 · 全景厅估计</span></div>'+trace('people',true);rail=metric('本空间人数',p===null?'未知':fmt(p)+' 人','临近摄像头 '+camera)+metric('声能水平',a===null?'未知':fmt(a,1,' dBFS'),'数字音频 · 未校准')+metric('人数数据年龄',c?fmt(cameraAge(c,'detection'),1,' 秒'):'未知')+metric('语义数据',semanticFresh(localSemantic())?'结果可用':'数据过期 / 等待更新');}
if(n===2){left='<h1>感知，走向理解</h1><p class="lead">视觉与声音提供证据，模型提供可追溯的解释。</p>'+semanticBlock()+trace('sound',true);rail=metric('临近摄像头',c?camera+' · '+c.location_name:camera)+metric('声音表达',a===null?'等待数据':fmt(a,1,' dBFS'),'实际采样趋势')+metric('空间语义',semanticFresh(localSemantic())?'模型推断':'等待有效证据')+metric('数据边界','感知 ≠ 事实','人数与类别均为模型估计');}
if(n===3){left='<h1>理解，支持响应</h1><p class="lead">从观测到空间模型，再到人的判断与系统编排。</p><div class="pipeline"><span>感知输入</span><b>→</b><span>空间表征</span><b>→</b><span>授权响应</span></div>'+gpu()+'<p class="note">此画面观察系统状态。认知推断保留不确定性；现场动作由既有控制系统与人的授权决定。</p>'+algorithms();rail=metric('视觉推理',visionFresh()?fmt(vision.metrics?.fps,1,' FPS'):'等待数据','整体服务吞吐')+metric('推理耗时',visionFresh()?fmt(vision.metrics?.infer_ms,1,' ms'):'等待数据')+metric('研发源 · 声学事件密度',acousticValue('T01'),'未来场景麦克风 1 · 非全景厅')+metric('环境校准','待实测','声压与空间传递需校准');}
return '<div><div class="eyebrow">CONTINUOUS SPACE · '+String(n).padStart(2,'0')+' / 03</div><div class="chapter">百音全景厅 · 此刻的空间</div>'+left+state(good,good?'有效数据正在进入画面':'数据等待 / 过期 · 保留连续空间视觉')+'</div><aside class="rail"><div class="eyebrow">LOCAL PERCEPTION</div><div class="chapter">临近感知 · '+camera+'</div>'+rail+'</aside>';}
function render(){if(query.get('delivery')==='stream')document.getElementById('control').textContent='BaiPlayer 直播 · 采集至屏幕存在缓冲延迟';var key=mode+':'+page;content.style.animation=key===lastRenderKey?'none':'reveal .6s ease-out';lastRenderKey=key;var c=cameraData();document.body.dataset.page=page;document.body.dataset.mode=mode;document.body.classList.toggle('panorama',mode!=='pulse');document.getElementById('identity').textContent=mode==='pulse'?'AOS PULSE · LAGOOON':'AOS PULSE · PANORAMA';document.getElementById('node').textContent=(mode==='pulse'?'LAGOOON-PULSE-01':'PANORAMA-'+mode.replace('panorama',''))+' · '+camera+' · '+(c?c.location_name:'等待来源');content.innerHTML=mode==='pulse'?(page===0?home():detail()):panorama();document.getElementById('source').textContent='视觉感知源 · '+(visionFresh()?'实时采集':'等待 / 过期')+' · 原始帧 '+(vision?.frame?.id??'—')+(error?' · '+error:'')+' · 更新周期 2 秒';nav.innerHTML=mode==='pulse'?titles.map(function(t,i){return '<button aria-label="'+t+'" data-page="'+i+'" class="'+(i===page?'active':'')+'"></button>';}).join(''):'';Array.from(nav.children).forEach(function(el){el.onclick=function(){page=Number(el.dataset.page);lastInteraction=Date.now();render();};});}
function receive(packet){if(packet.kind==='acoustics'){acoustics=packet.error?null:packet.data;render();return;}if(packet.kind==='vision'){if(packet.error){error=packet.error;}else{var v=packet.data;if(!v||v.event_type!=='vision.result'||!['1.0','1.1','1.2','1.3','1.4'].includes(v.schema_version)){error='接口版本不支持';render();return;}vision=v;received=Date.now();error='';if(num(v.frame?.timestamp)!==null&&Math.abs(Date.now()/1000-v.frame.timestamp)<5)sourceClockOffset=v.frame.timestamp*1000-received;var c=cameraData(),id=v.frame?.id;if(id!==lastFrame){history.push({at:Date.now(),sound:sound(c),people:people(c)});history=history.filter(function(x){return x.at>Date.now()-180000;});lastFrame=id;}}}else if(packet.kind==='network'){if(packet.error){networkError=packet.error;}else{network=packet.data;networkReceived=Date.now();networkError='';}}render();}
function navigate(key){lastInteraction=Date.now();if(mode!=='pulse')return;if(key==='ArrowRight'||key==='ArrowDown')page=(page+1)%6;else if(key==='ArrowLeft'||key==='ArrowUp')page=(page+5)%6;else if(key==='Escape'||key==='Backspace')page=0;else if(key==='Enter'&&page===0)page=1;render();}
window.Pulse={receive:receive,navigate:navigate,status:function(){return {mode:mode,camera:camera,page:page,frame:vision?.frame?.id,visionLive:visionFresh(),people:people(cameraData()),sound:sound(cameraData()),semanticLive:semanticFresh(localSemantic()),samples:history.length,received:received,acousticsLive:acousticFresh(),acousticSource:acousticSource()?.id,acousticT01:acousticValue('T01')};}};
document.addEventListener('keydown',function(e){if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp','Escape','Backspace','Enter'].includes(e.key)){e.preventDefault();navigate(e.key);}});
function fit(){var s=Math.min(innerWidth/1920,innerHeight/1080),stage=document.getElementById('stage');stage.style.transform='scale('+s+')';stage.style.left=((innerWidth-1920*s)/2)+'px';stage.style.top=((innerHeight-1080*s)/2)+'px';}
window.addEventListener('resize',fit);fit();render();
setInterval(function(){document.getElementById('clock').textContent=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());if(!fixed&&Date.now()>=nextPage&&Date.now()-lastInteraction>=45000){page=(page+1)%6;nextPage=Date.now()+(page===0?18000:12000);}render();},1000);
if(location.protocol!=='file:'){var pending=false,np=false;setInterval(async function(){if(pending)return;pending=true;try{var r=await fetch('/api/vision',{cache:'no-store'}),j=await r.json();receive(r.ok?{kind:'vision',data:j}:{kind:'vision',error:j.error||'服务异常'});}catch(e){receive({kind:'vision',error:'连接中断'});}finally{pending=false;}},2000);setInterval(async function(){if(np)return;np=true;try{var r=await fetch('/api/network',{cache:'no-store'}),j=await r.json();receive(r.ok?{kind:'network',data:j}:{kind:'network',error:j.error||'网络来源不可用'});}catch(e){receive({kind:'network',error:'网络来源不可用'});}finally{np=false;}},15000);}
setInterval(async function(){try{var r=await fetch('/api/acoustics',{cache:'no-store'});acoustics=r.ok?await r.json():null;}catch(e){acoustics=null;}},2000);
var canvas=document.getElementById('field'),ctx=canvas.getContext('2d'),reduce=window.matchMedia('(prefers-reduced-motion:reduce)').matches,frameAt=0;
function field(t){if(!reduce&&t-frameAt>65){frameAt=t;if(canvas.width!==innerWidth||canvas.height!==innerHeight){canvas.width=innerWidth;canvas.height=innerHeight;}else ctx.clearRect(0,0,canvas.width,canvas.height);var w=canvas.width,h=canvas.height,c=cameraData(),a=sound(c),p=people(c),energy=a===null?.12:Math.max(.05,Math.min(.8,(a+80)/80)),segment=mode==='pulse'?0:(Number(mode.replace('panorama',''))-1),phase=((Date.now()+sourceClockOffset)/10000)%(2*Math.PI);ctx.strokeStyle='#c79770';ctx.lineWidth=.7;ctx.globalAlpha=.26;for(var i=0;i<5;i++){ctx.beginPath();for(var x=0;x<w;x+=8){var globalX=x/w+segment,y=h*(.45+i*.045)+h*(.05+energy*.065)*Math.sin(globalX*2+phase+i*.28);if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();}ctx.globalAlpha=.12;for(var n=0;n<3;n++){ctx.beginPath();ctx.arc(w*.74,h*.35,(h*.25+n*h*.08)*(1+.025*Math.sin(phase)),0,2*Math.PI);ctx.stroke();}}requestAnimationFrame(field);}requestAnimationFrame(field);
})();
